when function = enterName.EntryName = turPS 
then askPermission (games)

"Red Dead Redemption 2"
"Grand Theft Auto V"
"God of War"
"The Last of Us Part II"
"The Witcher 3: Wild Hunt"
"The Last of Us Part I"
"Marvel's Spiderman"
"Marvel's Spiderman: Miles Morales"
"Ghost of Tsushima"
"Uncharted 4: A Thief's End"
"Bloodborne"
"Dark Souls III"
"Persona 5 Royal"
"Final Fantasy VII Remake"
"Death Stranding"
"Returnal"
"Ratchet & Clank: Rift Apart"
"Gran Turismo 7"
"Astro's Playroom"
"Final Fantasy XVI"
"Marvel's Avengers"
"Ghostrunner"
"Control"
"Cyberpunk 2077"
"Assassin's Creed Valhalla"
"Watch Dogs: Legion"
"Hitman 3"
"Resident Evil Village"
"Monster Hunter: World"
"Street Fighter V"
"Tekken 7"
"Dragon Ball FighterZ"
"FIFA 22"
"NBA 2K21"
"Call of Duty: Warzone"
"Battlefield V"
"Overwatch"
"Fortnite"
"Destiny 2"
"Rainbow Six Siege"
"Among Us"
"Fall Guys: Ultimate Knockout"
"Ghost of Tsushima: Director's Cut"
"Return to Monkey Island"
"Little Big Planet 3"
"Gran Turismo Sport"
"Bloodborne: The Old Hunters"
"Dark Souls Remastered"
"Persona 5 Strikers"
"Final Fantasy XIV"
"Death Stranding: Director's Cut"
"Ratchet & Clank: QForce"
"Marvel's Guardians of the Galaxy"
"Returnal: Ascension"
"Final Fantasy VII Rebirth"
"Ghostwire: Tokyo"
"Gran Turismo 6"
"Astro Bot Rescue Mission"
"God of War: Ragnarok"

then let games = askPermission (games)
else 
    endInstant.end 
    end)
}